blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, is_published

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/view', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete'),
    path('<int:pk>/', is_published, name='is_published'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    email_verification,
    UserResetPasswordView,
    NotMailPageView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("reset-password/", UserResetPasswordView.as_view(), name="reset_password"),
    path("no-email/", NotMailPageView.as_view(), name="no_email"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Почта", help_text="Укажите почту",)
    phone = models.CharField(
        max_length=50,
        verbose_name="Телефон",
        help_text="Укажите номер телефона",
        blank=True,
        null=True,
    )
    avatar = models.ImageField(
        upload_to="users/image",
        blank=True,
        null=True,
        verbose_name="Фото",
        help_text="Загрузите фотографию",
    )
    country = models.CharField(
        max_length=50,
        verbose_name="Страна",
        help_text="Укажите страну",
        blank=True,
        null=True,
    )
    token = models.CharField(
        max_length=100, verbose_name="Тоken", null=True, blank=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from config.settings import EMAIL_HOST_USER
from catalog.views import UserLoginRequiredMixin
from users.form import UserRegisterForm, UserProfileForm, ResetPasswordForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение почты",
            message=f"Привет! Перейди по ссылке для подтверждения {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("catalog:product_list")

    def get_object(self, queryset=None):
        return self.request.user


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserResetPasswordView(UserLoginRequiredMixin, PasswordResetView):
    form_class = ResetPasswordForm
    template_name = "users/reset_password.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        try:
            user = User.objects.get(email=email)
            if user:
                password = User.objects.make_random_password(length=10)
                user.set_password(password)
                user.save()
                send_mail(
                    subject="Сброс пароля",
                    message=f" Ваш новый пароль {password}",
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[user.email],
                )
            return redirect(reverse("users:login"))
        except:
            return redirect(reverse("users:no_email"))


class NotMailPageView(UserLoginRequiredMixin, TemplateView):
    template_name = "users/no_email.html"

users/templates/users/login.html
 {% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-3">
            <div class="row">
                <div class="card mt-4">
                    <div class="card-header">
                        <h3 class="card-title">Вход</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>
                        <a href="{% url 'users:reset_password' %}" class="btn btn-success mt-2">
                            Восстановить пароль
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/no_email.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <div class="row text mt-4">
        <div class="col-12">
            <div class="col-6">
                <p>Такого пользователя нет. Проверьте правильность введенной электронной почты.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
 {% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-3">
            <div class="row">
                <div class="card mt-4">
                    <div class="card-header">
                        <h3 class="card-title">Регистрация</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Зарегистрировать</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_password.html
 {% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-3">
            <div class="row">
                <div class="card mt-4">
                    <div class="card-header">
                        <h3 class="card-title">Введите пароль</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Восстановить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
 {% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="col-3">
            <div class="row">
                <div class="card mt-4">
                    <div class="card-header">
                        <h3 class="card-title">Редактировать профиль</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}